language: python

python:
  - "3.6"

services: postgresql

addons:
  postgresql: "10"

env:
  - DJANGO=2.1

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE django_queries;" -U postgres
  - python manage.py migrate --noinput

script:
  - python manage.py test