language: python

python:
  - "3.6"

services: postgresql

addons:
  postgresql: "9.6"

env:
  - DJANGO=2.1

install:
  - pip install -r requirements.txt

before_script:
  - createdb -U postgres django_queries
  - python manage.py migrate --noinput

script:
  - python manage.py test